version: '3.9'

services:
  dev:
    container_name: nestjs_api_dev
    image: node:16.1@sha256:fc7a47442a743e34050576adea835cd0fec7f3f75039c9393010b1735d42cef9
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: yarn run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src
      - /usr/node_modules
    restart: unless-stopped
  prod:
    container_name: nestjs_api_prod
    image: node:16.1@sha256:fc7a47442a743e34050576adea835cd0fec7f3f75039c9393010b1735d42cef9
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: yarn run start:prod
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src
      - /usr/node_modules
    restart: unless-stopped

networks:
  nesjs-network: