version: "3.9"

services:
  dev:
    container_name: nestjs_api_dev
    build:
      context: ..
      target: development
      dockerfile: ./docker/Dockerfile
    command: yarn run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - ../src:/usr/app/src
      - /usr/app/node_modules
    restart: unless-stopped
  prod:
    container_name: nestjs_api_prod
    build:
      context: ..
      target: production
      dockerfile: ./docker/Dockerfile
    command: yarn run start:prod
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    networks:
      - nesjs-network
    volumes:
      - ../src:/usr/app/src
      - /usr/app/node_modules
    restart: unless-stopped

networks:
  nesjs-network:
